### ISSUE TITLE
One-click installation of Knowlg in AWS environment

### ISSUE THREAD

**Issue by pallakartheekreddy** [Sunbird-Knowlg/knowledge-platform#938]
# Project Details

## What is Sunbird Knowlg?
Sunbird Knowlg (pronounced as the word "knowledge") consists of a set of tools and services that enable you to organise, curate, create, and discover millions of assets. 

For example, organizations across multiple domains such as e-Commerce, OTT, Education etc can leverage Sunbird Knowlg building block to organise their content and knowledge assets as per their domain, create targeted collections, courses, programs, projects, video repository, etc.

More details are [here](https://knowlg.sunbird.org/learn/readme)

#### One-click installation of Knowlg in AWS environment

**Current Scenario:** Currently, one-click installation of Knowlg enabled in local & Azure environment using terraforms. 

**Acceptance Criteria:** Enhance Knowlg one-click installation scripts to support the AWS environment

## Learning Path
**Complexity**
Medium

**Skills Required**
Terraform, Kubernetes, Docker

**Name of Mentors**
@aimansharief @pallakartheekreddy

**Project size**
4 Weeks

## Milestones
- [ ] Understand Knowlg one-click installation scripts
- [ ] Enhance scripts to deploy Knowlg DBs in the AWS environment 
- [ ] Enhance scripts to deploy Knowlg Services in the AWS environment 
- [ ] Enhance scripts to deploy Knowlg Jobs in the AWS environment

**Comment by wasup-yash** [comment]
hey, I am interested in this project idea and looking forward to writing a proposal for the same, is there anything else like good first issues or references that I needed to know apart from the project setup?

**Comment by nitin1chandani** [comment]
Hello Mentors
I have gone through the project details for the "One-click installation of Knowlg in AWS environment" and I am highly interested in this project. I am excited about the opportunity to contribute to the enhancement of Knowlg installation scripts to support the AWS environment.

**Comment by chirag0002** [comment]
Hey, @aimansharief @pallakartheekreddy !!
I've carefully reviewed the project details provided above and it almost aligns perfectly with my interests and learnings. I'm excited about the opportunity to contribute and help improve the functionality and user experience. Count me in for collaborating and making a positive impact on this project!
Looking forward to submitting a proposal for the same.
