### ISSUE TITLE
Change of Graph Database for Sunbird Knowlg

### ISSUE THREAD

**Issue by pallakartheekreddy** [Sunbird-Knowlg/knowledge-platform#939]
# Project Details 

## What is Sunbird Knowlg?
Sunbird Knowlg (pronounced as the word "knowledge") consists of a set of tools and services that enable you to organise, curate, create, and discover millions of assets. 

For example, organizations across multiple domains such as e-Commerce, OTT, Education etc can leverage Sunbird Knowlg building block to organise their content and knowledge assets as per their domain, create targeted collections, courses, programs, projects, video repository, etc.

More details are [here](https://knowlg.sunbird.org/learn/readme)

## Features to be implemented

###Change of Graph Database for Sunbird Knowlg 

**Current Scenario:** 
We are using Neo4J 3.3 with HA Cluster setup. Neo4j Stopped releasing open-source versions after Neo4J 3.3 version. 

The Neo4j 3.3 version is outdated and there is no customer support for this version. Also, it runs with only Java 8. So, We need to have an alternative open-source graph database for Sunbird Knowlg.

[Janus Graph](https://janusgraph.org/) will be the right fit for Sunbird Knowlg to proceed further. 

**Acceptance Criteria:** 

- [ ] The Database layer in the Ontology engine module should implement DAC interfaces for Janus Graph.
- [ ] Graph DB transaction events generator should be implemented for Janus Graph.
     - [ ] It should follow the existing transaction events format to avoid compatibility issues.
     - [ ] Transaction events should be generated only for successful transactions.
- [ ] Cluster setup of Janus Graph should be tested with Ontology engine.
- [ ] Neo4j to Janus Graph data migration script.

# Learning Path

**Complexity**
Complex

**Skills Required**
Java, Graph DB Concepts, Neo4j, Neo4j Cypher, Janus 

**Name of Mentors**
@maheshkumargangula @pallakartheekreddy 

**Project size**
6 Weeks

# Milestones
- [ ] Understanding of the existing neo4j Ontology engine implementation
- [ ] Interface the Graph APIs Implementation.
- [ ] Exploring and setup of Janus Graph cluster
- [ ] Using [Janus Graph](https://janusgraph.org/) and deprecating Neo4J.
- [ ] Neo4J to Janus Graph Migration Script.

**Comment by DishaJain17** [comment]
Hello  @maheshkumargangula , @pallakartheekreddy , My name is Disha Jain, and I'm excited to be a part of this project. I'm currently looking for open issues to contribute to, and I would greatly appreciate it if you could suggest some for me to work on.

I have a strong technical background, particularly in the MERN stack, Java, C++, Linux, Git, and I also have a solid understanding of basics of YAML, Docker, and Kubernetes. I'm eager to utilize my skills and knowledge to contribute meaningfully to this project.

Resume:https://drive.google.com/file/d/1-mPdea8ZHQv7B19y0v8CDHl3rEJsowie/view?usp=drivesdk

Intro:
https://drive.google.com/file/d/1-8wHZN-0Ew3aojcU3xJm9MNUoWWrAoAI/view?usp=drivesdk

Blogs:https://hashnode.com/@disha390

LinkedIn: https://www.linkedin.com/in/disha-jain-90a554229

Thank you in advance for your support and recommendations. I'm looking forward to hearing from you soon!
